### ISSUE TITLE
Example project: sudo lein cljs-lambda deploy || Subprocess failed

### ISSUE THREAD

**Issue by damesek** [nervous-systems/cljs-lambda#90]
Hi, 

lein cljs-lamdba deploy failed on Ubuntu 14.04. Could you help me what is the problem?

~/mylambda/my-lambda-project# sudo lein cljs-lambda deploy
WARNING: You're currently running as root; probably by accident.
Press control-C to abort or Enter to continue as root.
Set LEIN_ROOT to disable this warning.

Compiling "target/my-lambda-project/my_lambda_project.js" from ["src"]...
Compiling "target/my-lambda-project/my_lambda_project.js" failed.
clojure.lang.ExceptionInfo: failed compiling file:target/my-lambda-project/cljs_lambda/macros.cljc {:file #object[java.io.File 0x6c2658b "target/my-lambda-project/cljs_lambda/macros.cljc"]}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at cljs.compiler$compile_file$fn__3406.invoke(compiler.cljc:1372)
	at cljs.compiler$compile_file.invokeStatic(compiler.cljc:1338)
	at cljs.compiler$compile_file.invoke(compiler.cljc:1318)
	at cljs.closure$compile_file.invokeStatic(closure.clj:473)
	at cljs.closure$compile_file.invoke(closure.clj:464)
	at cljs.closure$eval5143$fn__5144.invoke(closure.clj:540)
	at cljs.closure$eval5079$fn__5080$G__5068__5087.invoke(closure.clj:430)
	at cljs.closure$compile_from_jar.invokeStatic(closure.clj:522)
	at cljs.closure$compile_from_jar.invoke(closure.clj:510)
	at cljs.closure$eval5149$fn__5150.invoke(closure.clj:550)
	at cljs.closure$eval5079$fn__5080$G__5068__5087.invoke(closure.clj:430)
	at cljs.closure$compile_sources$iter__5264__5268$fn__5269.invoke(closure.clj:869)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:688)
	at clojure.core$next__4341.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3033)
	at clojure.core$doall.invokeStatic(core.clj:3039)
	at clojure.core$doall.invoke(core.clj:3039)
	at cljs.closure$compile_sources.invokeStatic(closure.clj:865)
	at cljs.closure$compile_sources.invoke(closure.clj:854)
	at cljs.closure$build.invokeStatic(closure.clj:1943)
	at cljs.closure$build.invoke(closure.clj:1882)
	at cljs.build.api$build.invokeStatic(api.clj:210)
	at cljs.build.api$build.invoke(api.clj:198)
	at cljs.build.api$build.invokeStatic(api.clj:201)
	at cljs.build.api$build.invoke(api.clj:198)
	at cljsbuild.compiler$compile_cljs$fn__5771.invoke(compiler.clj:60)
	at cljsbuild.compiler$compile_cljs.invokeStatic(compiler.clj:59)
	at cljsbuild.compiler$compile_cljs.invoke(compiler.clj:48)
	at cljsbuild.compiler$run_compiler.invokeStatic(compiler.clj:168)
	at cljsbuild.compiler$run_compiler.invoke(compiler.clj:122)
	at user$eval5908$iter__5944__5948$fn__5949$fn__5967.invoke(form-init46941676171948885.clj:1)
	at user$eval5908$iter__5944__5948$fn__5949.invoke(form-init46941676171948885.clj:1)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3024)
	at clojure.core$doall.invokeStatic(core.clj:3039)
	at clojure.core$doall.invoke(core.clj:3039)
	at user$eval5908.invokeStatic(form-init46941676171948885.clj:1)
	at user$eval5908.invoke(form-init46941676171948885.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: java.lang.ClassNotFoundException: java.util.concurrent.CompletableFuture, compiling:(promesa/impl/promise.cljc:1:1) in file target/my-lambda-project/cljs_lambda/macros.cljc {:tag :cljs/analysis-error}
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at clojure.core$ex_info.invoke(core.clj:4617)
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:580)
	at cljs.analyzer$error.invoke(analyzer.cljc:576)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:2616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:2605)
	at cljs.compiler$emit_source.invokeStatic(compiler.cljc:1239)
	at cljs.compiler$emit_source.invoke(compiler.cljc:1219)
	at cljs.compiler$compile_file_STAR_$fn__3383.invoke(compiler.cljc:1290)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1154)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1145)
	at cljs.compiler$compile_file_STAR_.invokeStatic(compiler.cljc:1279)
	at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1275)
	at cljs.compiler$compile_file$fn__3406.invoke(compiler.cljc:1360)
	... 60 more
Caused by: java.lang.ClassNotFoundException: java.util.concurrent.CompletableFuture, compiling:(promesa/impl/promise.cljc:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at promesa.core$eval8798$loading__5569__auto____8799.invoke(core.cljc:25)
	at promesa.core$eval8798.invokeStatic(core.cljc:25)
	at promesa.core$eval8798.invoke(core.cljc:25)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at cljs_lambda.macros$eval8792$loading__5569__auto____8793.invoke(macros.cljc:1)
	at cljs_lambda.macros$eval8792.invokeStatic(macros.cljc:1)
	at cljs_lambda.macros$eval8792.invoke(macros.cljc:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cljs.analyzer$ns_side_effects$fn__2118.invoke(analyzer.cljc:2541)
	at cljs.analyzer$ns_side_effects.invokeStatic(analyzer.cljc:2540)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:2513)
	at cljs.analyzer$analyze_STAR_$fn__2154.invoke(analyzer.cljc:2603)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$reduce.invoke(core.clj:6527)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:2603)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2593)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:2618)
	... 69 more
Caused by: java.lang.ClassNotFoundException: java.util.concurrent.CompletableFuture
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2181)
	at promesa.impl.promise$eval8804$loading__5569__auto____8805.invoke(promise.cljc:25)
	at promesa.impl.promise$eval8804.invokeStatic(promise.cljc:25)
	at promesa.impl.promise$eval8804.invoke(promise.cljc:25)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6916)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 157 more
Subprocess failed

**Comment by moea** [comment]
@damesek `promesa`, a dependency of the cljs-lambda runtime library, uses java.util.CompletableFuture, which means that JDK8 or newer is required.  Although cljs-lambda only uses the promise functionality on Node, `promesa` exposes JVM functionality, which looks like it's causing this issue during compilation.  Is upgrading JDK a practical option for you?

**Comment by damesek** [comment]
Thanks for the quick answer! I try it now, no problem to upgrade.

**Comment by damesek** [comment]
Thanks works! Sorry for this delayed answer.
