### ISSUE TITLE
java.io.IOException: Cannot run program "aws": error=2, No such file or directory

### ISSUE THREAD

**Issue by JimLynchCodes** [nervous-systems/cljs-lambda#97]
When I run _lein cljs-lambda invoke work-magic_ with any arguments it always returns this:

```
jims-first-cljs-lambda ♘ lein cljs-lambda invoke work-magic
aws lambda invoke /var/folders/41/b5ntx4mn2mv9qk3jyxnsnk_w0000gn/T/lambda-output1140111309954810249.json --function-name work-magic --payload  --log-type Tail --query LogResult --output text
java.io.IOException: Cannot run program "aws": error=2, No such file or directory
 at java.lang.ProcessBuilder.start (ProcessBuilder.java:1048)
    java.lang.Runtime.exec (Runtime.java:620)
    clojure.java.shell$sh.invokeStatic (shell.clj:113)
    clojure.java.shell$sh.doInvoke (shell.clj:79)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:652)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.cljs_lambda.aws$aws_cli_BANG_.invokeStatic (aws.clj:72)
    leiningen.cljs_lambda.aws$aws_cli_BANG_.doInvoke (aws.clj:69)
    clojure.lang.RestFn.invoke (RestFn.java:445)
    clojure.core$partial$fn__4759.invoke (core.clj:2516)
    leiningen.cljs_lambda.aws$invoke_BANG_.invokeStatic (aws.clj:247)
    leiningen.cljs_lambda.aws$invoke_BANG_.invoke (aws.clj:235)
    leiningen.cljs_lambda$invoke.invokeStatic (cljs_lambda.clj:188)
    leiningen.cljs_lambda$invoke.invoke (cljs_lambda.clj:184)
    leiningen.cljs_lambda$cljs_lambda.invokeStatic (cljs_lambda.clj:230)
    leiningen.cljs_lambda$cljs_lambda.doInvoke (cljs_lambda.clj:214)
    clojure.lang.RestFn.invoke (RestFn.java:442)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__5932.doInvoke (main.clj:272)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:322)
    leiningen.core.main$apply_task.invoke (main.clj:308)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
    leiningen.core.main$_main$fn__5998.invoke (main.clj:401)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:482)
    clojure.lang.Var.invoke (Var.java:401)
    clojure.lang.AFn.applyToHelper (AFn.java:171)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
Caused by: java.io.IOException: error=2, No such file or directory
 at java.lang.UNIXProcess.forkAndExec (UNIXProcess.java:-2)
    java.lang.UNIXProcess.<init> (UNIXProcess.java:247)
    java.lang.ProcessImpl.start (ProcessImpl.java:134)
    java.lang.ProcessBuilder.start (ProcessBuilder.java:1029)
    java.lang.Runtime.exec (Runtime.java:620)
    clojure.java.shell$sh.invokeStatic (shell.clj:113)
    clojure.java.shell$sh.doInvoke (shell.clj:79)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:652)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.cljs_lambda.aws$aws_cli_BANG_.invokeStatic (aws.clj:72)
    leiningen.cljs_lambda.aws$aws_cli_BANG_.doInvoke (aws.clj:69)
    clojure.lang.RestFn.invoke (RestFn.java:445)
    clojure.core$partial$fn__4759.invoke (core.clj:2516)
    leiningen.cljs_lambda.aws$invoke_BANG_.invokeStatic (aws.clj:247)
    leiningen.cljs_lambda.aws$invoke_BANG_.invoke (aws.clj:235)
    leiningen.cljs_lambda$invoke.invokeStatic (cljs_lambda.clj:188)
    leiningen.cljs_lambda$invoke.invoke (cljs_lambda.clj:184)
    leiningen.cljs_lambda$cljs_lambda.invokeStatic (cljs_lambda.clj:230)
    leiningen.cljs_lambda$cljs_lambda.doInvoke (cljs_lambda.clj:214)
    clojure.lang.RestFn.invoke (RestFn.java:442)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__5932.doInvoke (main.clj:272)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:322)
    leiningen.core.main$apply_task.invoke (main.clj:308)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
    leiningen.core.main$_main$fn__5998.invoke (main.clj:401)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:482)
    clojure.lang.Var.invoke (Var.java:401)
    clojure.lang.AFn.applyToHelper (AFn.java:171)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```

I am running on mac 10.11.6 with Leiningen 2.7.1 on Java 1.8.0_121 Java HotSpot(TM) 64-Bit Server VM

**Comment by moea** [comment]
Do you get that error after having successfully executed the commands to build and deploy the Lambda function you're attempting to invoke?

If not, you'll need an AWS CLI install (`pip install awscli; aws configure`) for cljs-lambda to delegate to, and will need to deploy the function with `lein cljs-lambda deploy` prior to invoking.

In the event that you successfully deployed the function using cljs-lambda's serverless integration, you'll still need `awscli` if you want to use `lein cljs-lambda invoke`.

**Comment by JimLynchCodes** [comment]
Thanks, but when I try "pip install awscli" it returns errors, even with sudo:

```
The directory '/Users/jameslynch/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/jameslynch/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting awscli
  Downloading awscli-1.11.177-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 1.1MB/s 
Collecting docutils>=0.10 (from awscli)
  Downloading docutils-0.14-py2-none-any.whl (543kB)
    100% |████████████████████████████████| 552kB 2.2MB/s 
Collecting s3transfer<0.2.0,>=0.1.9 (from awscli)
  Downloading s3transfer-0.1.11-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 9.9MB/s 
Collecting botocore==1.7.35 (from awscli)
  Downloading botocore-1.7.35-py2.py3-none-any.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 348kB/s 
Collecting colorama<=0.3.7,>=0.2.5 (from awscli)
  Downloading colorama-0.3.7-py2.py3-none-any.whl
Requirement already satisfied: PyYAML<=3.12,>=3.10 in /Library/Python/2.7/site-packages (from awscli)
Collecting rsa<=3.5.0,>=3.1.2 (from awscli)
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 5.6MB/s 
Collecting futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" (from s3transfer<0.2.0,>=0.1.9->awscli)
  Downloading futures-3.1.1-py2-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1 (from botocore==1.7.35->awscli)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 4.6MB/s 
Collecting jmespath<1.0.0,>=0.7.1 (from botocore==1.7.35->awscli)
  Downloading jmespath-0.9.3-py2.py3-none-any.whl
Requirement already satisfied: pyasn1>=0.1.3 in /Library/Python/2.7/site-packages (from rsa<=3.5.0,>=3.1.2->awscli)
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore==1.7.35->awscli)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: docutils, futures, six, python-dateutil, jmespath, botocore, s3transfer, colorama, rsa, awscli
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-uEjr5o-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by JimLynchCodes** [comment]
`lein cljs-lambda default-iam-role` gives me same errors as original post. :(

**Comment by moea** [comment]
Yeah, anything that communicates with AWS using the `aws` cli will give you those errors, until you successfully install it.  Try adding `--ignore-installed six` to the `pip` invocation - I've seen that error before.

Details here on setting up the AWS CLI: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

**Comment by JimLynchCodes** [comment]
thanks @moea.

For anyone else having this problem, I had to install aws cli again:
`sudo pip install awscli --ignore-installed six`

and run the configure command:
`aws configure`
